from __future__ import annotations


DASHBOARD_HTML = r"""<!doctype html>
<html lang="id">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>IDX Data</title>
  <meta name="application-name" content="Market Data Dashboard">
  <style>
    :root{color-scheme:light;--ink:#17212b;--muted:#64748b;--line:#e2e8f0;--soft:#f8fafc;--accent:#0f766e;--accent-dark:#115e59;--danger:#b42318;--success:#18794e;--shadow:0 8px 24px rgba(15,23,42,.06)}
    *{box-sizing:border-box}[hidden]{display:none!important}body{margin:0;background:#f8fafc;color:var(--ink);font:14px/1.5 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}button,input,select{font:inherit}
    .shell{min-height:100vh}.topbar{height:58px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 max(20px,calc((100vw - 1120px)/2))}.brand{display:flex;align-items:center;gap:10px;font-weight:800;letter-spacing:.01em}.mark{display:grid;place-items:center;width:30px;height:30px;border-radius:8px;background:var(--accent);color:#fff;font-size:15px}.connection{display:flex;align-items:center;gap:8px;color:var(--muted);font-size:12px}.dot{width:8px;height:8px;border-radius:50%;background:#22c55e;box-shadow:0 0 0 4px rgba(34,197,94,.12)}
    main{width:min(1120px,calc(100% - 32px));margin:30px auto 64px}.hero{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;margin-bottom:22px}.hero h1{font-size:30px;line-height:1.15;margin:0 0 7px;letter-spacing:-.02em}.hero p{margin:0;color:var(--muted);max-width:650px}.hero-actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}
    .panel{background:#fff;border:1px solid var(--line);border-radius:12px;box-shadow:var(--shadow)}.panel-head{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:18px 20px;border-bottom:1px solid var(--line)}.panel-head h2{font-size:17px;line-height:1.25;margin:0}.panel-head p{font-size:12px;color:var(--muted);margin:3px 0 0}.panel-body{padding:20px}
    .filters-panel{border:2px solid #cce7e3;box-shadow:0 8px 24px rgba(15,118,110,.07);margin-bottom:18px}.filters-panel .panel-head{border-bottom:0;padding-bottom:8px}.filter-grid{display:grid;grid-template-columns:minmax(0,1.5fr) 170px 170px auto;gap:12px;align-items:end}.field{display:grid;gap:6px}.field label{font-size:12px;font-weight:750;color:#334155}.field input,.field select{width:100%;height:42px;border:1px solid #cbd5e1;border-radius:8px;padding:0 11px;background:#fff;color:var(--ink);outline:none}.field input:focus,.field select:focus{border-color:var(--accent);box-shadow:0 0 0 3px rgba(15,118,110,.12)}.field-help{font-size:11px;color:var(--muted);margin-top:2px}.range-row{display:flex;align-items:center;gap:7px;flex-wrap:wrap;margin-top:12px}.range-label{font-size:12px;color:var(--muted);margin-right:2px}.range-btn{border:1px solid var(--line);background:var(--soft);color:#334155;border-radius:7px;padding:6px 10px;cursor:pointer;font-size:12px}.range-btn:hover,.range-btn.active{border-color:#99d3cc;background:#e8f6f3;color:#0f5d57}.filter-footer{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:14px}.filter-state{font-size:12px;color:var(--muted)}
    .btn{min-height:40px;border:0;border-radius:8px;padding:0 15px;font-weight:750;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;gap:7px;white-space:nowrap}.btn:disabled,.btn.disabled{opacity:.5;cursor:not-allowed;pointer-events:none}.btn-primary{background:var(--accent);color:#fff}.btn-primary:hover{background:var(--accent-dark)}.btn-secondary{background:#e8eef9;color:#183b76}.btn-quiet{background:#f1f5f9;color:#334155}.btn-danger{background:#fff1f0;color:var(--danger);border:1px solid #fecaca}.export-actions{display:flex;gap:8px;flex-wrap:wrap}.export-actions a{text-decoration:none}.small-btn{min-height:34px;padding:0 11px;font-size:12px}
    .notice{display:none;margin:0 0 16px;padding:11px 14px;border-radius:8px;border:1px solid;font-size:13px}.notice.show{display:block}.notice.info{background:#eff6ff;border-color:#bfdbfe;color:#1e40af}.notice.error{background:#fff1f0;border-color:#fecaca;color:#991b1b}.notice.success{background:#ecfdf5;border-color:#bbf7d0;color:#166534}
    .result-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.result-title{display:flex;align-items:baseline;gap:9px;flex-wrap:wrap}.result-title h2{margin:0;font-size:18px}.result-count{font-size:12px;color:var(--muted)}.result-meta{font-size:12px;color:var(--muted);margin-top:3px}.table-wrap{margin-top:16px;border:1px solid var(--line);border-radius:9px;overflow:auto;max-height:520px}table{width:100%;border-collapse:collapse;min-width:700px}th{position:sticky;top:0;z-index:1;background:#f1f8f7;color:#185c55;text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:.045em;padding:11px 10px;border-bottom:1px solid #c7e1dd}td{padding:11px 10px;border-bottom:1px solid #eef2f4;white-space:nowrap;font-variant-numeric:tabular-nums}tbody tr:hover{background:#f8fbfb}.number{text-align:right}.empty{padding:46px 20px;text-align:center;color:var(--muted)}
    .results-panel{margin-bottom:18px}.result-actions{display:flex;gap:8px;flex-wrap:wrap}.status-line{display:flex;align-items:center;gap:8px;font-size:12px;color:var(--muted);margin-top:12px}.status-dot{width:7px;height:7px;border-radius:50%;background:#94a3b8}.status-dot.ready{background:#22c55e}.status-dot.busy{background:#f59e0b}.table-help{font-size:12px;color:var(--muted);margin:12px 0 0}
    .summary-strip{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0 18px}.summary-item{border:1px solid var(--line);border-radius:9px;background:#fff;padding:12px 14px}.summary-item span{display:block;color:var(--muted);font-size:11px}.summary-item strong{display:block;font-size:17px;margin-top:2px}
    details{background:#fff;border:1px solid var(--line);border-radius:12px;box-shadow:var(--shadow);margin-top:14px}details>summary{list-style:none;cursor:pointer;display:flex;align-items:center;justify-content:space-between;gap:16px;padding:16px 20px;font-weight:800}details>summary::-webkit-details-marker{display:none}details>summary:after{content:'+';font-size:20px;font-weight:400;color:var(--muted)}details[open]>summary:after{content:'−'}details>summary small{display:block;color:var(--muted);font-size:12px;font-weight:400;margin-top:3px}.details-body{padding:0 20px 20px;border-top:1px solid var(--line)}
    .section-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;padding-top:18px}.action-card{border:1px solid var(--line);border-radius:9px;padding:15px}.action-card h3{font-size:14px;margin:0 0 5px}.action-card p{font-size:12px;color:var(--muted);margin:0 0 13px}.action-row{display:flex;gap:8px;align-items:end}.action-row .field{flex:1}.action-row .btn{min-height:42px}.backfill-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.backfill-grid .wide{grid-column:1/-1}.job{margin-top:16px;padding-top:15px;border-top:1px solid var(--line)}.badge{display:inline-flex;border-radius:99px;padding:4px 9px;font-size:11px;font-weight:800}.RUNNING{background:#fff7d6;color:#8a5b00}.SUCCESS{background:#dcfce7;color:var(--success)}.FAILED{background:#fee2e2;color:var(--danger)}pre{max-height:170px;overflow:auto;background:#111827;color:#d1fae5;border-radius:8px;padding:12px;font:11px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace;white-space:pre-wrap;word-break:break-word}.runs{margin-top:18px}.runs h3{font-size:14px;margin:0 0 5px}.run-line{display:grid;grid-template-columns:1fr auto;gap:10px;padding:10px 0;border-bottom:1px solid #edf0f2}.run-title{font-weight:700;font-size:13px}.run-meta{font-size:11px;color:var(--muted)}
    .analysis-tabs{display:flex;gap:7px;flex-wrap:wrap;padding-top:18px}.analysis-tab{border:1px solid var(--line);background:#f8fafc;color:#334155;border-radius:7px;padding:8px 11px;font-weight:750;cursor:pointer;font-size:12px}.analysis-tab.active{background:var(--accent);color:#fff;border-color:var(--accent)}.analysis-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-top:14px}.analysis-kpi{border:1px solid var(--line);border-radius:9px;padding:11px;background:#fbfefd}.analysis-kpi strong{display:block;font-size:18px;margin-top:3px}.analysis-kpi span{font-size:10px;color:var(--muted);text-transform:uppercase;font-weight:750}.analysis-note{color:var(--muted);font-size:12px;margin:10px 0 0}.analysis-table{max-height:420px}.broker-tools{margin-top:20px;padding-top:18px;border-top:1px solid var(--line)}.broker-tools-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.broker-tools h3{margin:0;font-size:15px}.broker-tools p{margin:3px 0 0;color:var(--muted);font-size:12px}.broker-controls{display:flex;gap:8px;align-items:end;margin-top:12px}.broker-controls select{height:38px;border:1px solid #cbd5e1;border-radius:8px;padding:0 10px;background:#fff}.import-grid{display:grid;grid-template-columns:1fr 1fr auto;gap:8px;align-items:end}.import-grid select,.import-grid input[type=file]{width:100%;height:40px;border:1px solid #cbd5e1;border-radius:8px;padding:8px;background:#fff;color:var(--ink)}
    .footer-note{font-size:12px;color:var(--muted);margin-top:22px;text-align:center}.kbd{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:11px;background:#f1f5f9;border:1px solid #e2e8f0;border-radius:4px;padding:2px 5px}
    @media(max-width:850px){.filter-grid{grid-template-columns:1fr 1fr}.filter-grid .field:first-child{grid-column:1/-1}.filter-grid .btn{width:100%}.summary-strip{grid-template-columns:repeat(2,1fr)}.section-grid{grid-template-columns:1fr}.import-grid{grid-template-columns:1fr 1fr}.import-grid .btn{grid-column:1/-1}}
    @media(max-width:560px){main{width:min(100% - 20px,1120px);margin-top:20px}.topbar{padding:0 14px}.connection span:last-child{display:none}.hero{flex-direction:column}.hero-actions{justify-content:flex-start}.hero h1{font-size:25px}.filter-grid{grid-template-columns:1fr}.filter-grid .field:first-child{grid-column:auto}.filter-footer{align-items:stretch;flex-direction:column}.filter-footer .btn{width:100%}.panel-head,.result-head{align-items:flex-start;flex-direction:column}.result-actions,.export-actions{width:100%}.result-actions .btn,.result-actions a{flex:1}.summary-strip{gap:7px}.summary-item{padding:10px}.analysis-summary{grid-template-columns:repeat(2,1fr)}.broker-tools-head{flex-direction:column}.broker-controls{align-items:stretch;flex-direction:column}.broker-controls .btn{width:100%}.backfill-grid{grid-template-columns:1fr}.backfill-grid .wide{grid-column:auto}.import-grid{grid-template-columns:1fr}.import-grid .btn{grid-column:auto;width:100%}details>summary{padding:14px 15px}.details-body{padding:0 15px 15px}}
  </style>
  <style id="redesign-v2">
    /* IDX Data workspace redesign: compact navigation, one clear primary result, and calmer detail surfaces. */
    :root{color-scheme:light;--ink:#12233f;--muted:#64748b;--line:#dbe4ef;--soft:#f5f8fc;--accent:#2563eb;--accent-dark:#1d4ed8;--success:#12805c;--danger:#c2413b;--navy:#10233f;--shadow:0 12px 32px rgba(18,35,63,.07)}
    body{background:#eef3f8;color:var(--ink)}
    .topbar{height:72px;background:var(--navy);border-bottom:0;color:#fff;padding:0 max(24px,calc((100vw - 1320px)/2));position:sticky;top:0;z-index:30;box-shadow:0 6px 18px rgba(15,23,42,.14)}
    .brand{font-size:16px;color:#fff}.mark{width:36px;height:36px;border-radius:11px;background:#fff;color:var(--accent);font-size:16px;box-shadow:0 5px 14px rgba(0,0,0,.12)}.connection{color:#d7e2f1}.connection .dot{width:9px;height:9px;box-shadow:0 0 0 4px rgba(34,197,94,.18)}
    main{width:min(1320px,calc(100% - 40px));margin:26px auto 64px}
    .hero{margin-bottom:16px;padding:22px 24px;border:1px solid #d9e3ef;border-radius:12px;background:#fff;box-shadow:0 7px 20px rgba(18,35,63,.045)}.hero h1{font-size:29px;line-height:1.2;letter-spacing:-.025em;color:#12233f}.hero p{max-width:680px;color:#64748b}.hero-kicker{margin:0 0 6px;color:#64748b;font-size:10px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.hero-meta{display:flex;gap:0;flex-wrap:wrap;margin-top:11px}.hero-meta span{border:0;background:transparent;color:#6a7c93;border-radius:0;padding:0;font-size:11px;font-weight:650}.hero-meta span+span:before{content:'•';margin:0 13px;color:#b4c1d1}.hero-actions{align-items:flex-start}.hero-actions .btn{min-height:38px}
    .section-nav{position:sticky;top:72px;z-index:20;display:flex;align-items:center;gap:6px;overflow:auto;margin:0 0 15px;padding:7px;border:1px solid #d9e3ef;border-radius:13px;background:rgba(255,255,255,.94);box-shadow:0 6px 18px rgba(18,35,63,.06);backdrop-filter:blur(10px)}.section-nav button{border:0;background:transparent;color:#52657d;border-radius:9px;padding:9px 14px;cursor:pointer;white-space:nowrap;font-size:12px;font-weight:800}.section-nav button:hover,.section-nav button[aria-selected=true]{background:#eaf2ff;color:#1d4ed8}.section-nav .nav-spacer{flex:1;min-width:10px}.section-nav .nav-hint{color:#8493a7;font-size:11px;white-space:nowrap;padding:0 8px}.tab-panel[hidden]{display:none!important}.tab-panel.is-active{animation:tab-in .16s ease-out}details.tab-panel:not(.overview-details)>summary{display:none}details.tab-panel:not(.overview-details)>.details-body{border-top:0;padding-top:21px}@keyframes tab-in{from{opacity:.7;transform:translateY(2px)}to{opacity:1;transform:translateY(0)}}
    .panel,details{border:1px solid #d9e3ef;border-radius:16px;box-shadow:none}.filters-panel{border:1px solid #cdddf0;background:#fff;box-shadow:0 10px 28px rgba(37,99,235,.08);margin-bottom:15px}.filters-panel .panel-head{padding:20px 22px 8px}.filters-panel .panel-body{padding:14px 22px 21px}.panel-head h2{color:#12233f}.filter-grid{grid-template-columns:minmax(0,1.8fr) 170px 170px 150px;gap:10px}.field label{color:#344a66}.field input,.field select{height:44px;border-color:#cbd7e6;border-radius:10px}.field input:focus,.field select:focus{border-color:#6b9eef;box-shadow:0 0 0 3px rgba(37,99,235,.12)}.range-row{margin-top:13px}.range-btn{border-color:#d9e3ef;background:#f8fafc;border-radius:8px}.range-btn:hover,.range-btn.active{border-color:#9abcf4;background:#eaf2ff;color:#1d4ed8}.filter-footer{margin-top:12px}
    .btn{min-height:42px;border-radius:10px;padding:0 16px}.btn-primary{background:var(--accent)}.btn-primary:hover{background:var(--accent-dark)}.btn-secondary{background:#e9f1ff;color:#1e4b95}.btn-quiet{background:#edf2f7;color:#3f536d}.btn-danger{background:#fff3f2;color:#b42318;border-color:#fecaca}
    .notice{border-radius:11px;margin-bottom:14px}
    .results-panel{margin-bottom:15px;overflow:hidden;box-shadow:0 14px 34px rgba(18,35,63,.08)}.results-panel .panel-body{padding:0}.result-head{padding:21px 23px 14px;border-bottom:1px solid #e8eef5}.result-title h2{font-size:20px;color:#10233f}.result-meta{color:#6a7c93}.status-line{padding:11px 23px 0}.table-help{padding:0 23px;margin-top:10px}.table-wrap{margin:0 23px 23px;border-color:#dbe4ef;border-radius:12px;max-height:530px}th{background:#f1f6fb;color:#294e78;border-bottom-color:#d6e2ef;padding:12px 11px}td{padding:12px 11px}.table-wrap table{min-width:960px}tbody tr:hover{background:#f4f8fc}
    .summary-strip{grid-template-columns:repeat(4,1fr);gap:10px;margin:15px 0 0}.summary-item{border-color:#dbe4ef;border-radius:12px;background:#fbfdff;padding:13px 15px}.summary-item span{color:#71839a}.summary-item strong{font-size:18px;color:#10233f}
    details{margin-top:12px;background:#fff;overflow:hidden}details>summary{padding:17px 21px;color:#1d3554}details>summary small{color:#71839a}details[open]>summary{background:#f8fafc;border-bottom:1px solid #e4ebf3}.details-body{padding:0 21px 21px;border-top:0}
    .section-grid{padding-top:16px;gap:12px}.action-card{border-color:#dbe4ef;border-radius:12px;background:#fbfdff;padding:16px}.action-card h3{color:#1a3557}.action-card p{color:#6a7c93}.job{border-top-color:#e4ebf3}.runs{margin-top:20px}
    .analysis-tabs{padding-top:16px;gap:6px}.analysis-tab{border-color:#d9e3ef;background:#f6f8fb;border-radius:9px;padding:9px 13px}.analysis-tab.active{background:var(--accent);border-color:var(--accent)}.analysis-summary{gap:10px;margin-top:14px}.analysis-kpi{border-color:#dbe4ef;border-radius:12px;background:#fbfdff;padding:13px}.analysis-kpi strong{color:#10233f}.analysis-table{max-height:430px}
    .broker-tools{margin-top:18px;padding-top:18px;border-top-color:#e4ebf3}.broker-tools h3{color:#1a3557}.broker-controls{margin-top:13px}.broker-controls select{height:40px;border-color:#cbd7e6;border-radius:9px}.import-grid select,.import-grid input[type=file]{height:42px;border-color:#cbd7e6;border-radius:9px}
    .footer-note{margin-top:20px;color:#71839a}
    @media(max-width:980px){.filter-grid{grid-template-columns:1fr 1fr}.filter-grid .field:first-child{grid-column:1/-1}.filter-grid .btn{width:100%}.hero{padding:24px}.section-nav .nav-hint{display:none}}
    @media(max-width:640px){main{width:min(100% - 20px,1320px);margin-top:16px}.topbar{padding:0 14px}.connection span:last-child{display:none}.hero{padding:21px 18px;border-radius:14px}.hero h1{font-size:27px}.hero-actions{width:100%;justify-content:flex-start}.section-nav{top:72px;margin-bottom:12px;border-radius:11px}.section-nav button{padding:8px 11px}.filter-grid{grid-template-columns:1fr}.filter-grid .field:first-child{grid-column:auto}.filters-panel .panel-head,.filters-panel .panel-body{padding-left:16px;padding-right:16px}.result-head,.status-line{padding-left:16px;padding-right:16px}.table-help{padding:0 16px}.table-wrap{margin-left:16px;margin-right:16px}.summary-strip{grid-template-columns:repeat(2,1fr)}.analysis-summary{grid-template-columns:repeat(2,1fr)}.details-body{padding-left:16px;padding-right:16px}.panel-head,.result-head{align-items:flex-start;flex-direction:column}.result-actions,.export-actions{width:100%}.result-actions .btn,.result-actions a{flex:1}.broker-controls{align-items:stretch;flex-direction:column}.broker-controls .btn{width:100%}}
  </style>
</head>
<body>
<div class="shell">
  <header class="topbar"><div class="brand"><div class="mark">ID</div><span>IDX Data</span></div><div class="connection"><span class="dot"></span><span id="connectionText">Menghubungkan database</span></div></header>
  <main>
    <section class="hero"><div><p class="hero-kicker">IDX DATA</p><h1>Data pasar IDX</h1><p>Pilih saham dan periode untuk menampilkan OHLCV, moving average, dan analisis pendukung.</p><div class="hero-meta"><span>Rupiah</span><span>Hari bursa</span><span>CSV / Excel</span></div></div><div class="hero-actions"><button class="btn btn-quiet" id="refreshAll">Muat ulang</button></div></section>
    <div class="notice" id="notice" aria-live="polite"></div>
    <nav class="section-nav" role="tablist" aria-label="Menu workspace"><button id="tab-results" role="tab" type="button" data-tab-target="results" aria-selected="true" aria-controls="resultsSection">Hasil data</button><button id="tab-analysis" role="tab" type="button" data-tab-target="analysis" aria-selected="false" aria-controls="analysisDetails">Analisis</button><button id="tab-backtest" role="tab" type="button" data-tab-target="backtest" aria-selected="false" aria-controls="backtestDetails">Validasi</button><button id="tab-broker" role="tab" type="button" data-tab-target="broker" aria-selected="false" aria-controls="brokerDetails">Broker</button><button id="tab-idx" role="tab" type="button" data-tab-target="idx" aria-selected="false" aria-controls="idxDetails">Data IDX</button><button id="tab-features" role="tab" type="button" data-tab-target="features" aria-selected="false" aria-controls="featureDetails">Data lanjutan</button><button id="tab-operations" role="tab" type="button" data-tab-target="operations" aria-selected="false" aria-controls="operationsDetails">Scraping</button><span class="nav-spacer"></span><span class="nav-hint">Pilih tab untuk mengganti tampilan</span></nav>

    <section class="panel filters-panel" aria-labelledby="filterTitle">
      <div class="panel-head"><div><h2 id="filterTitle">1. Pilih data</h2><p>Isi kode saham dan periode, lalu tekan Tampilkan.</p></div><button class="btn btn-quiet small-btn" id="resetView">Reset tampilan</button></div>
      <div class="panel-body">
        <form id="dataForm">
          <div class="filter-grid">
            <div class="field"><label for="symbols">Kode saham</label><input id="symbols" list="symbolOptions" value="BBCA, BBRI, TLKM" placeholder="Contoh: BBCA, BBRI, TLKM" autocomplete="off"><datalist id="symbolOptions"></datalist><div class="field-help">Ketik untuk memilih dari daftar IDX; pisahkan beberapa kode dengan koma atau spasi.</div></div>
            <div class="field"><label for="fromDate">Dari tanggal</label><input id="fromDate" type="date"></div>
            <div class="field"><label for="toDate">Sampai tanggal</label><input id="toDate" type="date"></div>
            <button class="btn btn-primary" type="submit">Tampilkan data</button>
          </div>
          <div class="range-row"><span class="range-label">Periode cepat:</span><button type="button" class="range-btn" data-range="7">7 hari</button><button type="button" class="range-btn" data-range="30">30 hari</button><button type="button" class="range-btn" data-range="90">90 hari</button><button type="button" class="range-btn" data-range="custom">Custom</button></div>
          <div class="filter-footer"><span class="filter-state" id="filterState">Belum ada filter diterapkan.</span><span class="filter-state">Tip: gunakan <span class="kbd">Tampilkan data</span> setelah mengubah filter.</span></div>
        </form>
      </div>
    </section>

    <section class="panel results-panel tab-panel is-active" id="resultsSection" data-tab-panel="results" role="tabpanel" aria-labelledby="tab-results">
      <div class="panel-body">
        <div class="result-head"><div><div class="result-title"><h2>2. Hasil OHLCV + MA</h2><span class="result-count" id="resultCount">Belum dimuat</span></div><div class="result-meta" id="dateRange">Pilih filter di atas untuk melihat data.</div></div><div class="result-actions"><a class="btn btn-secondary" id="csvLink" href="#">Unduh CSV</a><a class="btn btn-primary" id="xlsxLink" href="#">Unduh Excel</a></div></div>
        <div class="status-line"><span class="status-dot" id="resultDot"></span><span id="resultStatus">Belum ada permintaan data.</span></div>
        <p class="table-help">MA dihitung berdasarkan <strong>hari bursa</strong>, bukan hari kalender. MA50 menampilkan “—” sampai tersedia 50 candle valid.</p>
        <div class="table-wrap"><table><thead><tr><th>Simbol</th><th>Tanggal</th><th class="number">Open</th><th class="number">High</th><th class="number">Low</th><th class="number">Close</th><th class="number">MA5</th><th class="number">MA10</th><th class="number">MA20</th><th class="number">MA50</th><th class="number">Perubahan</th><th class="number">Volume</th></tr></thead><tbody id="dataBody"><tr><td class="empty" colspan="12">Isi filter lalu klik “Tampilkan data”.</td></tr></tbody></table></div>
      </div>
    </section>

    <details class="overview-details tab-panel" data-tab-panel="results" data-section="overview"><summary><div>Ringkasan database<small>Lihat jumlah candle dan status proses tanpa menghalangi hasil saham.</small></div></summary>
      <div class="details-body"><section class="summary-strip" aria-label="Ringkasan database"><div class="summary-item"><span>Candle tersimpan</span><strong id="totalRows">—</strong></div><div class="summary-item"><span>Saham tersimpan</span><strong id="totalSymbols">—</strong></div><div class="summary-item"><span>Data terbaru</span><strong id="latestDate">—</strong></div><div class="summary-item"><span>Proses terakhir</span><strong id="lastStatus">—</strong></div></section></div>
    </details>

    <details id="analysisDetails" class="tab-panel" data-tab-panel="analysis" data-section="analysis" role="tabpanel" aria-labelledby="tab-analysis"><summary><div>3. Analisis teknikal dan kuantitatif<small>MA5, MA10, MA20, MA50, serta tiga mode riset.</small></div></summary>
      <div class="details-body">
        <div class="panel-head" style="padding-left:0;padding-right:0"><div><h2>Analisis pada filter aktif</h2><p>Hasil ini membantu membaca data; bukan jaminan keuntungan.</p></div><div class="export-actions"><a class="btn btn-secondary small-btn" id="analysisCsvLink" href="#">CSV analisis</a><a class="btn btn-primary small-btn" id="analysisXlsxLink" href="#">Excel analisis</a></div></div>
        <div class="analysis-tabs" role="tablist"><button class="analysis-tab active" data-analysis-tab="technical">Data & MA</button><button class="analysis-tab" data-analysis-tab="simons">Multi-factor</button><button class="analysis-tab" data-analysis-tab="benter">Probability</button><button class="analysis-tab" data-analysis-tab="combined">Gabungan</button></div>
        <div class="analysis-summary"><div class="analysis-kpi"><span>MA50 terakhir</span><strong id="analysisMa50">—</strong></div><div class="analysis-kpi"><span>Score multi-factor</span><strong id="analysisSimons">—</strong></div><div class="analysis-kpi"><span>Probabilitas akhir</span><strong id="analysisProbability">—</strong></div><div class="analysis-kpi"><span>Data broker</span><strong id="analysisBroker">—</strong></div></div>
        <p class="analysis-note" id="analysisNote">Tampilkan data terlebih dahulu untuk menghitung indikator.</p>
        <div class="table-wrap analysis-table"><table><thead><tr><th>Simbol</th><th>Tanggal</th><th class="number">Close</th><th class="number">MA5</th><th class="number">MA10</th><th class="number">MA20</th><th class="number">MA50</th><th class="number">RSI14</th><th class="number">ATR14</th><th>Regime</th><th class="number">RS</th><th class="number">Score</th><th class="number" id="analysisProbabilityHeader">P Final</th><th>Sinyal</th></tr></thead><tbody id="analysisBody"><tr><td class="empty" colspan="14">Belum ada analisis.</td></tr></tbody></table></div>
      </div>
    </details>

    <details id="backtestDetails" class="tab-panel" data-tab-panel="backtest" data-section="backtest" role="tabpanel" aria-labelledby="tab-backtest"><summary><div>4. Validasi walk-forward dan sizing<small>Uji sinyal pada candle berikutnya tanpa memakai target masa depan sebagai fitur.</small></div></summary>
      <div class="details-body">
        <div class="broker-controls"><div class="field"><label for="backtestHorizon">Horizon hari bursa</label><select id="backtestHorizon"><option value="5">5</option><option value="10">10</option><option value="20">20</option></select></div><div class="field"><label for="backtestScore">Minimum score</label><input id="backtestScore" type="number" min="0" max="100" value="65"></div><div class="field"><label for="backtestProbability">Minimum probabilitas</label><input id="backtestProbability" type="number" min="0" max="1" step="0.05" value="0.55"></div><button class="btn btn-secondary" id="runBacktest" type="button">Jalankan validasi</button></div>
        <p class="analysis-note" id="backtestStatus">Pilih simbol dan tampilkan data terlebih dahulu.</p>
        <div class="analysis-summary"><div class="analysis-kpi"><span>Signals</span><strong id="backtestSignals">—</strong></div><div class="analysis-kpi"><span>Win rate</span><strong id="backtestWinRate">—</strong></div><div class="analysis-kpi"><span>Avg forward return</span><strong id="backtestReturn">—</strong></div><div class="analysis-kpi"><span>Max drawdown</span><strong id="backtestDrawdown">—</strong></div></div>
        <div class="broker-controls"><div class="field"><label for="sizeCapital">Modal (Rp)</label><input id="sizeCapital" type="number" min="1" value="100000000"></div><div class="field"><label for="sizeRisk">Risiko per posisi</label><input id="sizeRisk" type="number" min="0.001" max="1" step="0.005" value="0.01"></div><div class="field"><label for="sizeStop">ATR × stop</label><input id="sizeStop" type="number" min="0.1" max="10" step="0.1" value="2"></div><button class="btn btn-quiet" id="runPositionSize" type="button">Hitung ukuran posisi</button></div>
        <p class="analysis-note" id="positionSizeStatus">Ukuran posisi membutuhkan ATR dan harga dari baris analisis terakhir.</p>
        <p class="analysis-note">Hasil ini belum memasukkan fee, slippage, suspensi, kapasitas pasar, atau bias survivorship. Gunakan sebagai validasi riset.</p>
      </div>
    </details>

    <details id="brokerDetails" class="tab-panel" data-tab-panel="broker" data-section="broker" role="tabpanel" aria-labelledby="tab-broker"><summary><div>5. Data broker<small>Pilih salah satu: ringkasan seluruh pasar atau broker per saham.</small></div></summary>
      <div class="details-body">
        <div class="broker-tools"><div class="broker-tools-head"><div><h3>Ringkasan broker seluruh pasar</h3><p>Fungsinya melihat broker paling aktif di seluruh bursa pada hari tertentu. IDX publik hanya memberi total volume, nilai, dan frekuensi; tidak memberi saham apa yang dibeli atau sisi buyer/seller.</p></div><div class="export-actions"><a class="btn btn-secondary small-btn" id="marketBrokerCsvLink" href="#">CSV pasar</a><a class="btn btn-primary small-btn" id="marketBrokerXlsxLink" href="#">Excel pasar</a></div></div><div class="broker-controls"><div class="field"><label for="marketBrokerDays">Periode ringkasan</label><select id="marketBrokerDays"><option value="1">1 hari bursa</option><option value="5">5 hari bursa</option><option value="10">10 hari bursa</option></select></div><button class="btn btn-secondary" id="loadMarketBroker" type="button">Tampilkan ringkasan pasar</button></div><p class="analysis-note" id="marketBrokerStatus">Jalankan pengambilan data broker pada bagian “Operasi data” terlebih dahulu.</p><div class="table-wrap"><table><thead><tr><th>Rank</th><th>Broker</th><th class="number">Volume</th><th class="number">Nilai transaksi</th><th class="number">Frekuensi</th></tr></thead><tbody id="marketBrokerBody"><tr><td class="empty" colspan="5">Belum ada ringkasan broker pasar.</td></tr></table></div></div>
        <div class="broker-tools"><div class="broker-tools-head"><div><h3>Top 5 broker per saham</h3><p id="brokerScope">Pilih satu kode pada filter utama. Data ini menjawab broker mana yang paling banyak membeli/menjual saham tersebut.</p></div><div class="export-actions"><a class="btn btn-secondary small-btn" id="brokerCsvLink" href="#">CSV broker</a><a class="btn btn-primary small-btn" id="brokerXlsxLink" href="#">Excel broker</a></div></div><div class="broker-controls"><div class="field"><label for="brokerDays">Periode</label><select id="brokerDays"><option value="1">1 hari bursa</option><option value="5">5 hari bursa</option><option value="10">10 hari bursa</option></select></div><button class="btn btn-secondary" id="loadBroker" type="button">Tampilkan Top 5 broker</button></div><p class="analysis-note" id="brokerStatus">Gunakan satu kode saham pada filter utama.</p><div class="table-wrap"><table><thead><tr><th>Posisi</th><th>Broker</th><th class="number">Buy Vol</th><th class="number">Buy Value</th><th class="number">Avg Buy</th><th class="number">Sell Vol</th><th class="number">Sell Value</th><th class="number">Avg Sell</th><th class="number">Net Vol</th><th class="number">Net Value</th><th class="number">Buy Freq</th><th class="number">Sell Freq</th></tr></thead><tbody id="brokerBody"><tr><td class="empty" colspan="12">Belum ada data broker per saham.</td></tr></table></div></div>
        <div class="action-card" style="margin-top:18px"><h3>Impor dataset tambahan</h3><p>Gunakan CSV atau Excel dari sumber yang sah untuk broker per saham, order book, intraday, fundamental, event, atau berita. Impor tidak menghapus data lama.</p><div class="import-grid"><div class="field"><label for="importDataset">Jenis dataset</label><select id="importDataset"><option value="ohlcv">OHLCV dari ekspor IDX Data</option><option value="stock-summary">Stock Summary IDX</option><option value="benchmark">IHSG / benchmark kompatibilitas</option><option value="index-summary">Index Summary IDX</option><option value="foreign-flow">Foreign flow</option><option value="broker-summary">Broker per saham</option><option value="order-book">Order book snapshot</option><option value="intraday-trades">Intraday trades</option><option value="fundamentals">Fundamental kuartalan</option><option value="events">Kalender event</option><option value="news">Berita / sentiment</option></select></div><div class="field"><label for="importFile">File CSV atau Excel</label><input id="importFile" type="file" accept=".csv,.xlsx,.xlsm,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"></div><button class="btn btn-secondary" id="importButton" type="button">Impor file</button></div></div>
      </div>
    </details>

    <details id="idxDetails" class="tab-panel" data-tab-panel="idx" data-section="idx" role="tabpanel" aria-labelledby="tab-idx"><summary><div>6. Data IDX lengkap<small>Value, frequency, foreign volume, saham beredar, dan indeks resmi IDX.</small></div></summary>
      <div class="details-body">
        <div class="broker-tools"><div class="broker-tools-head"><div><h3>Stock Summary IDX</h3><p>Payload resmi IDX di luar candle dasar. Kolom yang tidak disediakan IDX tetap kosong.</p></div><div class="export-actions"><a class="btn btn-secondary small-btn" id="stockSummaryCsvLink" href="#">CSV Stock Summary</a><a class="btn btn-primary small-btn" id="stockSummaryXlsxLink" href="#">Excel Stock Summary</a></div></div><p class="analysis-note" id="stockSummaryStatus">Muat data saham terlebih dahulu.</p><div class="table-wrap"><table><thead><tr><th>Simbol</th><th>Tanggal</th><th>Nama Emiten</th><th class="number">Value</th><th class="number">Frequency</th><th class="number">Foreign Buy</th><th class="number">Foreign Sell</th><th class="number">Listed Shares</th><th class="number">Tradeable Shares</th></tr></thead><tbody id="stockSummaryBody"><tr><td class="empty" colspan="9">Belum ada Stock Summary.</td></tr></table></div></div>
        <div class="broker-tools"><div class="broker-tools-head"><div><h3>IHSG dan indeks IDX</h3><p>Benchmark untuk excess return, beta, korelasi, dan residual momentum.</p></div><div class="export-actions"><a class="btn btn-secondary small-btn" id="indexSummaryCsvLink" href="#">CSV indeks</a><a class="btn btn-primary small-btn" id="indexSummaryXlsxLink" href="#">Excel indeks</a></div></div><p class="analysis-note" id="indexSummaryStatus">Gunakan operasi “Ambil IHSG dan indeks IDX”.</p><div class="table-wrap"><table><thead><tr><th>Indeks</th><th>Tanggal</th><th class="number">Previous</th><th class="number">High</th><th class="number">Low</th><th class="number">Close</th><th class="number">Change</th><th class="number">Value</th><th class="number">Frequency</th></tr></thead><tbody id="indexSummaryBody"><tr><td class="empty" colspan="9">Belum ada data indeks.</td></tr></table></div></div>
        <div class="broker-tools"><h3>Coverage dataset</h3><p id="catalogStatus">Memuat status coverage…</p><div class="table-wrap"><table><thead><tr><th>Dataset</th><th>Status</th><th class="number">Rows</th><th>Sumber / catatan</th></tr></thead><tbody id="catalogBody"><tr><td class="empty" colspan="4">Memuat…</td></tr></table></div></div>
      </div>
    </details>

    <details id="featureDetails" class="tab-panel" data-tab-panel="features" data-section="features" role="tabpanel" aria-labelledby="tab-features"><summary><div>7. Data lanjutan per saham<small>Ringkas order book, intraday, fundamental, event, dan sentiment untuk simbol aktif.</small></div></summary>
      <div class="details-body">
        <div class="broker-tools-head" style="padding-top:18px"><div><h3 id="featureTitle">Pilih satu simbol untuk melihat data lanjutan</h3><p id="featureStatus">Dataset yang belum tersedia dari feed publik IDX akan ditandai “belum ada data”, bukan diisi dengan asumsi.</p></div><button class="btn btn-secondary" id="loadFeatures" type="button">Muat data lanjutan</button></div>
        <div class="analysis-summary"><div class="analysis-kpi"><span>Order book</span><strong id="featureOrderBook">—</strong></div><div class="analysis-kpi"><span>Intraday</span><strong id="featureIntraday">—</strong></div><div class="analysis-kpi"><span>Fundamental</span><strong id="featureFundamentals">—</strong></div><div class="analysis-kpi"><span>Event</span><strong id="featureEvents">—</strong></div></div>
        <div class="export-actions" style="padding-top:14px"><a class="btn btn-quiet small-btn" id="featureAdjustedLink" href="#">Adjusted OHLCV</a><a class="btn btn-quiet small-btn" id="featureOrderLink" href="#">Order book</a><a class="btn btn-quiet small-btn" id="featureIntradayLink" href="#">Intraday</a><a class="btn btn-quiet small-btn" id="featureFundamentalLink" href="#">Fundamental</a><a class="btn btn-quiet small-btn" id="featureEventLink" href="#">Event</a><a class="btn btn-quiet small-btn" id="featureNewsLink" href="#">News</a></div>
      </div>
    </details>

    <details id="operationsDetails" class="tab-panel" data-tab-panel="operations" data-section="operations" role="tabpanel" aria-labelledby="tab-operations"><summary><div>8. Operasi data<small>Gunakan hanya saat ingin mengambil atau memperbarui data dari IDX.</small></div></summary>
      <div class="details-body">
        <div class="section-grid">
          <div class="action-card"><h3>Perbarui daftar saham</h3><p>Ambil daftar emiten IDX dan verifikasi kode serta nama.</p><button class="btn btn-secondary job-button" data-job="sync">Ambil dan verifikasi saham</button></div>
          <div class="action-card"><h3>Ambil data terbaru</h3><p>Ambil hari perdagangan terbaru yang belum tersimpan.</p><div class="action-row"><div class="field"><label for="dailyEnd">Sampai tanggal</label><input type="date" id="dailyEnd"></div><button class="btn btn-primary job-button" data-job="daily">Ambil data terbaru</button></div></div>
          <div class="action-card"><h3>Ringkasan broker seluruh pasar</h3><p>Ambil total volume, nilai, dan frekuensi setiap broker dari IDX.</p><button class="btn btn-secondary job-button" data-job="market-broker">Ambil ringkasan broker pasar</button></div>
          <div class="action-card"><h3>IHSG dan indeks IDX</h3><p>Ambil indeks IDX serta buffer 60 hari sebelum periode agar minimal 21 hari bursa tersedia untuk regime.</p><button class="btn btn-secondary job-button" data-job="index-summary">Ambil IHSG dan indeks IDX</button></div>
          <div class="action-card"><h3>Corporate action</h3><p>Ambil split, bonus, rights, dividen, dan event penerbit yang tersedia untuk simbol terpilih.</p><div class="action-row"><div class="field"><label for="actionSymbols">Kode saham</label><input id="actionSymbols" value="BBCA, BBRI, TLKM"></div><button class="btn btn-secondary job-button" data-job="corporate-actions">Ambil event</button></div></div>
          <div class="action-card"><h3>Harga adjusted</h3><p>Materialisasikan harga adjusted dari corporate action split/bonus yang memiliki rasio valid.</p><div class="action-row"><div class="field"><label for="adjustSymbols">Kode saham</label><input id="adjustSymbols" value="BBCA, BBRI, TLKM"></div><button class="btn btn-secondary job-button" data-job="adjust">Bangun harga adjusted</button></div></div>
          <div class="action-card"><h3>Ambil data historis</h3><p>Gunakan untuk rentang dan kode saham tertentu. Maksimal 20 kode per proses.</p><form id="backfillForm" class="backfill-grid"><div class="field wide"><label for="backfillSymbols">Kode saham</label><input id="backfillSymbols" value="BBCA, BBRI, TLKM"></div><div class="field"><label for="backfillStart">Mulai</label><input id="backfillStart" type="date" required></div><div class="field"><label for="backfillEnd">Selesai</label><input id="backfillEnd" type="date" required></div><button class="btn btn-primary wide" type="submit">Mulai scraping historis</button></form></div>
        </div>
        <div class="job" id="jobPanel"><div id="jobSummary" class="run-meta">Belum ada proses scraping pada sesi ini.</div><pre id="jobOutput" hidden></pre></div>
        <div class="runs"><h3>Riwayat proses</h3><div id="runList"><div class="run-meta">Memuat riwayat…</div></div></div>
        <div style="display:flex;justify-content:flex-end;margin-top:16px"><button class="btn btn-danger small-btn" id="resetJob">Reset scraping</button></div>
      </div>
    </details>
    <p class="footer-note">Data berasal dari sumber IDX yang tersedia untuk aplikasi. Ringkasan broker pasar tidak sama dengan Top 5 broker pembeli/penjual per saham.</p>
  </main>
</div>
<script>
  const byId = id => document.getElementById(id);
  const rupiah = new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0});
  const integer = new Intl.NumberFormat('id-ID');
  const percent = new Intl.NumberFormat('id-ID',{style:'percent',minimumFractionDigits:2,maximumFractionDigits:2});
  const viewResetKey = 'idx-data:view-reset:v1';
  const scrapingResetKey = 'idx-data:scraping-reset:v1';
  let jobTimer;
  let analysisRows=[];
  let analysisTab='technical';
  let symbolCatalog={};
  let dataReady=false;
  let brokerReady=false;
  let marketBrokerReady=false;

  function isoDate(value){return value.toISOString().slice(0,10)}
  function isReset(key){try{return localStorage.getItem(key)==='1'}catch{return false}}
  function rememberReset(key){try{localStorage.setItem(key,'1')}catch{}}
  function forgetReset(key){try{localStorage.removeItem(key)}catch{}}
  function setDefaults(){const now=new Date();const before=new Date(now);before.setDate(now.getDate()-7);if(isReset(viewResetKey)){byId('symbols').value='';byId('fromDate').value='';byId('toDate').value=''}else{byId('symbols').value='BBCA, BBRI, TLKM';byId('toDate').value=isoDate(now);byId('fromDate').value=isoDate(before)}if(isReset(scrapingResetKey)){byId('dailyEnd').value='';byId('backfillSymbols').value='';byId('backfillStart').value='';byId('backfillEnd').value=''}else{byId('dailyEnd').value=isoDate(now);byId('backfillSymbols').value='BBCA, BBRI, TLKM';byId('backfillEnd').value=isoDate(now);byId('backfillStart').value=isoDate(before)}}
  function showNotice(message,type='info'){const node=byId('notice');node.className=`notice show ${type}`;node.textContent=message;clearTimeout(node._timer);node._timer=setTimeout(()=>node.className='notice',5000)}
  async function api(url,options={}){const response=await fetch(url,options);let payload;try{payload=await response.json()}catch{payload={detail:await response.text()}}if(!response.ok)throw new Error(payload.detail||`HTTP ${response.status}`);return payload}
  function query(){const params=new URLSearchParams();const symbols=byId('symbols').value.trim();if(symbols)params.set('symbols',symbols);if(byId('fromDate').value)params.set('from',byId('fromDate').value);if(byId('toDate').value)params.set('to',byId('toDate').value);return params}
  function selectedSymbols(){return byId('symbols').value.split(/[ ,\s]+/).map(item=>item.trim().toUpperCase()).filter(Boolean)}
  function setLinkGroupEnabled(ids,enabled){for(const id of ids){const link=byId(id);link.classList.toggle('disabled',!enabled);link.setAttribute('aria-disabled',String(!enabled));if(!enabled)link.href='#'}}
  function setExportsEnabled(enabled){setLinkGroupEnabled(['csvLink','xlsxLink'],enabled)}
  function setAnalysisExportsEnabled(enabled){setLinkGroupEnabled(['analysisCsvLink','analysisXlsxLink'],enabled)}
  function setBrokerExportsEnabled(enabled){setLinkGroupEnabled(['brokerCsvLink','brokerXlsxLink'],enabled)}
  function setMarketBrokerExportsEnabled(enabled){setLinkGroupEnabled(['marketBrokerCsvLink','marketBrokerXlsxLink'],enabled)}
  function setFeatureExportsEnabled(enabled){setLinkGroupEnabled(['stockSummaryCsvLink','stockSummaryXlsxLink','indexSummaryCsvLink','indexSummaryXlsxLink','featureAdjustedLink','featureOrderLink','featureIntradayLink','featureFundamentalLink','featureEventLink','featureNewsLink'],enabled)}
  function brokerQuery(){const symbol=selectedSymbols()[0]||'';const params=new URLSearchParams();if(symbol)params.set('symbol',symbol);if(byId('fromDate').value)params.set('from',byId('fromDate').value);if(byId('toDate').value)params.set('to',byId('toDate').value);params.set('days',byId('brokerDays').value);return params}
  function marketBrokerQuery(){const params=new URLSearchParams();if(byId('fromDate').value)params.set('from',byId('fromDate').value);if(byId('toDate').value)params.set('to',byId('toDate').value);params.set('days',byId('marketBrokerDays').value);return params}
  function updateFilterState(){const symbols=selectedSymbols();const from=byId('fromDate').value;const to=byId('toDate').value;byId('filterState').textContent=symbols.length&&from&&to?`${symbols.length} kode saham • ${from} sampai ${to}`:'Belum ada filter lengkap.'}
  function updateExportLinks(){const params=query();const hasSymbols=selectedSymbols().length>0;byId('csvLink').href=`/export/ohlcv.csv?${params}`;byId('xlsxLink').href=`/export/ohlcv.xlsx?${params}`;byId('analysisCsvLink').href=`/export/analysis.csv?${params}`;byId('analysisXlsxLink').href=`/export/analysis.xlsx?${params}`;byId('stockSummaryCsvLink').href=`/export/stock-summary.csv?${params}`;byId('stockSummaryXlsxLink').href=`/export/stock-summary.xlsx?${params}`;const indexParams=new URLSearchParams();if(byId('fromDate').value)indexParams.set('from',byId('fromDate').value);if(byId('toDate').value)indexParams.set('to',byId('toDate').value);byId('indexSummaryCsvLink').href=`/export/index-summary.csv?${indexParams}`;byId('indexSummaryXlsxLink').href=`/export/index-summary.xlsx?${indexParams}`;const featureParams=new URLSearchParams();if(hasSymbols)featureParams.set('symbols',selectedSymbols().join(','));if(byId('fromDate').value)featureParams.set('from',byId('fromDate').value);if(byId('toDate').value)featureParams.set('to',byId('toDate').value);[['featureAdjustedLink','adjusted-ohlcv'],['featureOrderLink','order-book'],['featureIntradayLink','intraday-trades'],['featureFundamentalLink','fundamentals'],['featureEventLink','events'],['featureNewsLink','news']].forEach(([id,dataset])=>{byId(id).href=`/export/feature/${dataset}.xlsx?${featureParams}`});const brokerParams=brokerQuery();byId('brokerCsvLink').href=`/export/broker-summary.csv?${brokerParams}`;byId('brokerXlsxLink').href=`/export/broker-summary.xlsx?${brokerParams}`;const marketParams=marketBrokerQuery();byId('marketBrokerCsvLink').href=`/export/market-broker-summary.csv?${marketParams}`;byId('marketBrokerXlsxLink').href=`/export/market-broker-summary.xlsx?${marketParams}`;setExportsEnabled(hasSymbols&&dataReady);setAnalysisExportsEnabled(hasSymbols&&dataReady);setBrokerExportsEnabled(hasSymbols&&dataReady&&brokerReady);setMarketBrokerExportsEnabled(marketBrokerReady);setFeatureExportsEnabled(dataReady)}
  function analysisNumber(value,kind='price'){if(value===null||value===undefined||value==='')return '—';if(kind==='percent')return percent.format(Number(value));if(kind==='number')return integer.format(Number(value));return rupiah.format(Number(value))}
  // Keep the displayed probability aligned with the selected model. In
  // particular, never show p_model under the P Final heading when the IHSG
  // benchmark is not available yet.
  function renderAnalysis(){
    const body=byId('analysisBody');
    const probabilityHeader=byId('analysisProbabilityHeader');
    if(probabilityHeader)probabilityHeader.textContent=analysisTab==='benter'?'P Model':'P Final';
    if(!analysisRows.length){
      body.innerHTML='<tr><td class="empty" colspan="14">Belum ada hasil analisis.</td></tr>';
      byId('analysisMa50').textContent='—';
      byId('analysisSimons').textContent='—';
      byId('analysisProbability').textContent='—';
      byId('analysisBroker').textContent='—';
      return;
    }
    const visible=analysisRows.slice(-500);
    body.innerHTML=visible.map(row=>{
      const score=row.ensemble_score??row.simons_score;
      const probability=analysisTab==='benter'?row.p_model:row.p_final;
      let status=row.data_status==='ready'?row.entry_signal:'Belum cukup data';
      if(analysisTab==='benter')status=row.probability_status||'Belum cukup data';
      if(analysisTab==='combined'){
        status=probability==null
          ?(row.benchmark_status||row.probability_status||'Benchmark belum siap')
          :(score!=null&&score>=65&&probability>=.6?'Konfluensi positif':'Perlu validasi');
      }
      return `<tr><td><strong>${row.symbol}</strong></td><td>${row.trade_date}</td><td class="number">${analysisNumber(row.close)}</td><td class="number">${analysisNumber(row.ma5)}</td><td class="number">${analysisNumber(row.ma10)}</td><td class="number">${analysisNumber(row.ma20)}</td><td class="number">${analysisNumber(row.ma50)}</td><td class="number">${analysisNumber(row.rsi14,'number')}</td><td class="number">${analysisNumber(row.atr14)}</td><td>${row.market_regime||'—'}</td><td class="number">${analysisNumber(row.relative_strength_rank,'percent')}</td><td class="number">${analysisTab==='technical'?'—':analysisNumber(score,'number')}</td><td class="number">${analysisTab==='technical'?'—':analysisNumber(probability,'percent')}</td><td>${status}</td></tr>`;
    }).join('');
    const latest=analysisRows[analysisRows.length-1];
    byId('analysisMa50').textContent=analysisNumber(latest.ma50);
    byId('analysisSimons').textContent=latest.ensemble_score==null?'—':`${Number(latest.ensemble_score).toFixed(1)}/100`;
    byId('analysisProbability').textContent=latest.p_final==null?'—':percent.format(Number(latest.p_final));
    byId('analysisBroker').textContent=latest.broker_net_value==null?'Belum diimpor':'Tersedia';
    byId('analysisNote').textContent=`${latest.benchmark_status||latest.probability_status||'Hasil riset baseline'} • ${latest.entry_signal||'Belum cukup data'}${latest.price_source==='adjusted'?' • harga adjusted':''}`;
  }
  async function loadAnalysis(){if(isReset(viewResetKey)){analysisRows=[];renderAnalysis();return}try{analysisRows=await api(`/ui/api/analysis?${query()}&limit=5000`);renderAnalysis()}catch(error){analysisRows=[];renderAnalysis();byId('analysisNote').textContent=error.message}}
  async function loadBroker(){const symbols=selectedSymbols();brokerReady=false;if(symbols.length!==1){byId('brokerStatus').textContent=symbols.length?'Pilih tepat satu kode saham pada filter utama.':'Isi satu kode saham pada filter utama.';byId('brokerScope').textContent='Pilih satu kode pada filter utama.';byId('brokerBody').innerHTML='<tr><td class="empty" colspan="12">Pilih tepat satu kode saham untuk melihat broker.</td></tr>';setBrokerExportsEnabled(false);return}const params=brokerQuery();const symbol=symbols[0];const company=symbolCatalog[symbol]?.company_name;const companyLabel=company?` — ${String(company).replace(/\.+$/,'')}`:'';byId('brokerScope').textContent=`${symbol}${companyLabel}. Data ini menjawab broker mana yang paling banyak membeli/menjual saham tersebut.`;byId('brokerStatus').textContent='Memuat data broker per saham…';try{const data=await api(`/ui/api/broker-summary?${params}`);const rows=[...(data.top_buyers||[]).map(row=>({...row,position:'Buyer'})),...(data.top_sellers||[]).map(row=>({...row,position:'Seller'}))];brokerReady=rows.length>0&&data.data_status==='ready';byId('brokerBody').innerHTML=rows.length?rows.map(row=>`<tr><td>${row.position}</td><td><strong>${row.broker_code}</strong>${row.broker_name?` — ${row.broker_name}`:''}</td><td class="number">${integer.format(row.buy_volume||0)}</td><td class="number">${rupiah.format(row.buy_value||0)}</td><td class="number">${analysisNumber(row.buy_average)}</td><td class="number">${integer.format(row.sell_volume||0)}</td><td class="number">${rupiah.format(row.sell_value||0)}</td><td class="number">${analysisNumber(row.sell_average)}</td><td class="number">${integer.format(row.net_volume||0)}</td><td class="number" style="color:${Number(row.net_value)<0?'#b42318':'#18794e'}">${rupiah.format(row.net_value||0)}</td><td class="number">${integer.format(row.buy_frequency||0)}</td><td class="number">${integer.format(row.sell_frequency||0)}</td></tr>`).join(''):'<tr><td class="empty" colspan="12">Belum ada data broker per saham.</td></tr>';byId('brokerStatus').textContent=data.data_status==='ready'?`Periode: ${(data.trading_dates||[]).join(', ')}`:data.data_status;updateExportLinks()}catch(error){byId('brokerStatus').textContent=error.message;byId('brokerBody').innerHTML='<tr><td class="empty" colspan="12">Data broker per saham belum tersedia.</td></tr>';setBrokerExportsEnabled(false)}}
  async function loadMarketBroker(){const params=marketBrokerQuery();marketBrokerReady=false;byId('marketBrokerStatus').textContent='Memuat ringkasan broker pasar…';try{const data=await api(`/ui/api/market-broker-summary?${params}`);const rows=data.rows||[];marketBrokerReady=rows.length>0&&data.data_status==='ready';byId('marketBrokerBody').innerHTML=rows.length?rows.slice(0,25).map((row,index)=>`<tr><td>${index+1}</td><td><strong>${row.broker_code}</strong>${row.broker_name?` — ${row.broker_name}`:''}</td><td class="number">${integer.format(row.volume||0)}</td><td class="number">${rupiah.format(row.value||0)}</td><td class="number">${integer.format(row.frequency||0)}</td></tr>`).join(''):'<tr><td class="empty" colspan="5">Belum ada ringkasan broker pasar.</td></tr>';byId('marketBrokerStatus').textContent=data.data_status==='ready'?`Periode: ${(data.trading_dates||[]).join(', ')} • Menampilkan ${Math.min(rows.length,25)} dari ${rows.length} broker.`:data.data_status;updateExportLinks()}catch(error){byId('marketBrokerStatus').textContent=error.message;byId('marketBrokerBody').innerHTML='<tr><td class="empty" colspan="5">Ringkasan broker pasar belum tersedia.</td></tr>';setMarketBrokerExportsEnabled(false)}}
  async function loadStockSummary(){if(!dataReady){return}try{const rows=await api(`/ui/api/stock-summary?${query()}&limit=500`);byId('stockSummaryBody').innerHTML=rows.length?rows.slice(-200).map(row=>`<tr><td><strong>${row.symbol}</strong></td><td>${row.trade_date}</td><td>${row.company_name||'—'}</td><td class="number">${row.value==null?'—':rupiah.format(row.value)}</td><td class="number">${row.frequency==null?'—':integer.format(row.frequency)}</td><td class="number">${row.foreign_buy_volume==null?'—':integer.format(row.foreign_buy_volume)}</td><td class="number">${row.foreign_sell_volume==null?'—':integer.format(row.foreign_sell_volume)}</td><td class="number">${row.listed_shares==null?'—':integer.format(row.listed_shares)}</td><td class="number">${row.tradeable_shares==null?'—':integer.format(row.tradeable_shares)}</td></tr>`).join(''):'<tr><td class="empty" colspan="9">Belum ada Stock Summary untuk filter ini.</td></tr>';byId('stockSummaryStatus').textContent=`${integer.format(rows.length)} baris Stock Summary IDX.`}catch(error){byId('stockSummaryStatus').textContent=error.message}}
  async function loadIndexSummary(){try{const params=new URLSearchParams();if(byId('fromDate').value)params.set('from',byId('fromDate').value);if(byId('toDate').value)params.set('to',byId('toDate').value);const rows=await api(`/ui/api/index-summary?${params}&limit=500`);byId('indexSummaryBody').innerHTML=rows.length?rows.slice(-200).map(row=>`<tr><td><strong>${row.benchmark}</strong></td><td>${row.trade_date}</td><td class="number">${row.previous==null?'—':Number(row.previous).toFixed(2)}</td><td class="number">${row.highest==null?'—':Number(row.highest).toFixed(2)}</td><td class="number">${row.lowest==null?'—':Number(row.lowest).toFixed(2)}</td><td class="number">${Number(row.close).toFixed(2)}</td><td class="number">${row.change==null?'—':Number(row.change).toFixed(2)}</td><td class="number">${row.value==null?'—':rupiah.format(row.value)}</td><td class="number">${row.frequency==null?'—':integer.format(row.frequency)}</td></tr>`).join(''):'<tr><td class="empty" colspan="9">Belum ada data indeks.</td></tr>';byId('indexSummaryStatus').textContent=`${integer.format(rows.length)} baris indeks IDX.`}catch(error){byId('indexSummaryStatus').textContent='Belum ada data indeks otomatis.'}}
  async function loadCatalog(){try{const data=await api('/ui/api/data-catalog');const rows=Object.entries(data);byId('catalogBody').innerHTML=rows.map(([name,item])=>`<tr><td><strong>${name}</strong></td><td>${item.status}</td><td class="number">${integer.format(item.rows||0)}</td><td>${item.source}</td></tr>`).join('');byId('catalogStatus').textContent='Status dataset diperbarui.'}catch(error){byId('catalogStatus').textContent=error.message}}
  async function loadFeatures(){const symbol=selectedSymbols()[0];if(!symbol){byId('featureStatus').textContent='Isi satu kode saham pada filter utama terlebih dahulu.';return}byId('featureTitle').textContent=`Data lanjutan ${symbol}`;byId('featureStatus').textContent='Memuat ringkasan…';try{const params=new URLSearchParams({symbol});if(byId('toDate').value)params.set('date',byId('toDate').value);const data=await api(`/ui/api/symbol-features?${params}`);const order=data.order_book||{};const intraday=data.intraday||{};const fundamentals=data.fundamentals||{};const events=data.events||{};byId('featureOrderBook').textContent=order.status==='ready'?`${order.levels} level • imbalance ${order.imbalance==null?'—':percent.format(order.imbalance)}`:'Belum ada';byId('featureIntraday').textContent=intraday.status==='ready'?`${integer.format(intraday.trades)} trade • VWAP ${intraday.vwap==null?'—':rupiah.format(intraday.vwap)}`:'Belum ada';byId('featureFundamentals').textContent=fundamentals.status==='ready'?`${fundamentals.latest_period} • margin ${fundamentals.net_margin==null?'—':percent.format(fundamentals.net_margin)}`:'Belum ada';byId('featureEvents').textContent=events.status==='ready'?`${integer.format(events.count)} event`:'Belum ada';byId('featureStatus').textContent='Ringkasan diperbarui. Detail dapat diunduh dari tombol dataset.'}catch(error){byId('featureStatus').textContent=error.message}}
  async function runBacktest(){if(!selectedSymbols().length){byId('backtestStatus').textContent='Isi minimal satu simbol.';return}const params=query();params.set('horizon',byId('backtestHorizon').value);params.set('score_threshold',byId('backtestScore').value);params.set('probability_threshold',byId('backtestProbability').value);byId('backtestStatus').textContent='Menjalankan walk-forward…';try{const data=await api(`/ui/api/backtest?${params}`);byId('backtestSignals').textContent=integer.format(data.signals||0);byId('backtestWinRate').textContent=data.win_rate==null?'—':percent.format(data.win_rate);byId('backtestReturn').textContent=data.average_forward_return==null?'—':percent.format(data.average_forward_return);byId('backtestDrawdown').textContent=data.max_drawdown==null?'—':percent.format(data.max_drawdown);byId('backtestStatus').textContent=data.status==='ready'?`Model ${data.model_version}; ${data.warning}`:'Data belum cukup untuk sinyal dan horizon ini.'}catch(error){byId('backtestStatus').textContent=error.message}}
  async function runPositionSize(){const latest=analysisRows[analysisRows.length-1];if(!latest){byId('positionSizeStatus').textContent='Tampilkan analisis terlebih dahulu.';return}const params=new URLSearchParams({capital:byId('sizeCapital').value,risk_fraction:byId('sizeRisk').value,stop_multiple:byId('sizeStop').value});if(latest.atr14!=null)params.set('atr',latest.atr14);if(latest.close!=null)params.set('price',latest.close);try{const data=await api(`/ui/api/position-size?${params}`);byId('positionSizeStatus').textContent=data.status==='ready'?`Saran riset: ${integer.format(data.shares)} saham • nilai ${rupiah.format(data.notional)} • jarak stop ${rupiah.format(data.stop_distance)}.`:'ATR/harga belum cukup untuk menghitung.'}catch(error){byId('positionSizeStatus').textContent=error.message}}
  async function loadSymbols(){try{const rows=await api('/symbols');symbolCatalog=Object.fromEntries(rows.map(row=>[row.symbol,row]));byId('symbolOptions').innerHTML=rows.map(row=>`<option value="${row.symbol}">${row.company_name||''}</option>`).join('')}catch(error){/* symbol suggestions are optional */}}
  async function loadOverview(){try{const data=await api('/ui/api/overview');byId('totalRows').textContent=integer.format(data.total_rows);byId('totalSymbols').textContent=integer.format(data.total_symbols);byId('latestDate').textContent=data.latest_date||'—';byId('dateRange').textContent=isReset(viewResetKey)?'Pilih filter di atas untuk melihat data.':(data.earliest_date?`${data.earliest_date} — ${data.latest_date}`:'Belum ada data');byId('lastStatus').textContent=data.last_run?.status||'—';byId('connectionText').textContent='Database terhubung'}catch(error){byId('connectionText').textContent='Database bermasalah';showNotice(error.message,'error')}}
  async function loadData(){const body=byId('dataBody');dataReady=false;brokerReady=false;marketBrokerReady=false;setExportsEnabled(false);setAnalysisExportsEnabled(false);setBrokerExportsEnabled(false);setMarketBrokerExportsEnabled(false);if(isReset(viewResetKey)){body.innerHTML='<tr><td class="empty" colspan="12">Tampilan direset. Isi filter lalu klik “Tampilkan data”.</td></tr>';byId('resultStatus').textContent='Tampilan dikosongkan.';byId('resultCount').textContent='Belum dimuat';byId('resultDot').className='status-dot';analysisRows=[];renderAnalysis();return}updateFilterState();body.innerHTML='<tr><td class="empty" colspan="12">Memuat data…</td></tr>';byId('resultStatus').textContent='Memuat data dari database…';byId('resultDot').className='status-dot busy';try{const rows=await api(`/ui/api/ohlcv?${query()}&limit=2000`);if(!rows.length){body.innerHTML='<tr><td class="empty" colspan="12">Tidak ada data pada filter ini.</td></tr>';byId('resultStatus').textContent='Tidak ada data yang cocok.';byId('resultCount').textContent='0 baris';byId('resultDot').className='status-dot';analysisRows=[];renderAnalysis();return}body.innerHTML=rows.map(row=>{const change=Number(row.open)?(Number(row.close)-Number(row.open))/Number(row.open):0;return `<tr><td><strong>${row.symbol}</strong></td><td>${row.trade_date}</td><td class="number">${rupiah.format(row.open)}</td><td class="number">${rupiah.format(row.high)}</td><td class="number">${rupiah.format(row.low)}</td><td class="number">${rupiah.format(row.close)}</td><td class="number">${analysisNumber(row.ma5)}</td><td class="number">${analysisNumber(row.ma10)}</td><td class="number">${analysisNumber(row.ma20)}</td><td class="number">${analysisNumber(row.ma50)}</td><td class="number" style="color:${change<0?'#b42318':'#18794e'}">${percent.format(change)}</td><td class="number">${integer.format(row.volume)}</td></tr>`}).join('');dataReady=true;updateExportLinks();byId('resultStatus').textContent='Data berhasil dimuat.';byId('resultCount').textContent=`${integer.format(rows.length)} baris`;byId('resultDot').className='status-dot ready';byId('dateRange').textContent=rows.length?`${rows[0].trade_date} sampai ${rows[rows.length-1].trade_date}`:'—';loadAnalysis();loadStockSummary()}catch(error){body.innerHTML=`<tr><td class="empty" colspan="12">${error.message}</td></tr>`;byId('resultStatus').textContent='Data gagal dimuat.';byId('resultDot').className='status-dot';analysisRows=[];renderAnalysis()}}
  async function loadRuns(){try{const runs=await api('/ui/api/etl-runs?limit=6');byId('runList').innerHTML=runs.length?runs.map(run=>`<div class="run-line"><div><div class="run-title">${run.job_name}</div><div class="run-meta">Loaded ${integer.format(run.rows_loaded)} • Rejected ${integer.format(run.rows_rejected)}</div></div><span class="badge ${run.status}">${run.status}</span></div>`).join(''):'<div class="run-meta">Belum ada riwayat.</div>'}catch(error){byId('runList').innerHTML=`<div class="run-meta">${error.message}</div>`}}
  function setJobButtons(disabled){document.querySelectorAll('.job-button,#backfillForm button').forEach(button=>button.disabled=disabled)}
  function renderJob(job){const output=byId('jobOutput');const reset=byId('resetJob');if(!job){setJobButtons(false);byId('jobSummary').textContent='Belum ada proses scraping pada sesi ini.';output.hidden=true;output.textContent='';reset.disabled=false;return}const running=job.status==='RUNNING';setJobButtons(running);reset.disabled=running;byId('jobSummary').innerHTML=`<span class="badge ${job.status}">${job.status}</span> <strong>${job.name}</strong><div class="run-meta">${job.command}</div>`;output.hidden=!job.output;output.textContent=job.output||'';if(running){clearTimeout(jobTimer);jobTimer=setTimeout(pollJob,2500)}else{loadOverview();loadRuns();loadData();if(job.name&&job.name.toLowerCase().includes('broker'))loadMarketBroker()}}
  async function pollJob(){try{renderJob(await api('/ui/api/jobs/current'))}catch(error){showNotice(error.message,'error')}}
  async function runJob(url,payload){try{const job=await api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:payload?JSON.stringify(payload):undefined});forgetReset(scrapingResetKey);showNotice(`${job.name} dimulai.`,'success');renderJob(job)}catch(error){showNotice(error.message,'error')}}
  async function resetJob(){try{await api('/ui/api/jobs/reset',{method:'POST'});clearTimeout(jobTimer);rememberReset(scrapingResetKey);byId('dailyEnd').value='';byId('backfillSymbols').value='';byId('backfillStart').value='';byId('backfillEnd').value='';renderJob(null);showNotice('Status scraping direset. Data tersimpan tidak dihapus.','success')}catch(error){showNotice(error.message,'error')}}
  function resetView(){rememberReset(viewResetKey);setActiveTab('results');dataReady=false;byId('symbols').value='';byId('fromDate').value='';byId('toDate').value='';byId('dataBody').innerHTML='<tr><td class="empty" colspan="12">Tampilan direset. Isi filter lalu klik “Tampilkan data”.</td></tr>';byId('resultStatus').textContent='Tampilan dikosongkan.';byId('resultCount').textContent='Belum dimuat';byId('dateRange').textContent='Pilih filter di atas untuk melihat data.';byId('resultDot').className='status-dot';setExportsEnabled(false);setAnalysisExportsEnabled(false);setBrokerExportsEnabled(false);analysisRows=[];renderAnalysis();updateFilterState();showNotice('Filter dan hasil tampilan sudah dikosongkan.','success')}
  async function importCsv(){const file=byId('importFile').files[0];if(!file){showNotice('Pilih file CSV atau Excel terlebih dahulu.','error');return}const dataset=byId('importDataset').value;try{let result;if(/\.(xlsx|xlsm|xls)$/i.test(file.name)){const body=new FormData();body.append('upload',file);result=await api(`/ui/api/import-upload/${dataset}`,{method:'POST',body})}else{const content=await file.text();result=await api(`/ui/api/import/${dataset}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content,source:file.name})})}showNotice(`${result.rows_loaded} baris berhasil diimpor.`,'success');if(result.rows_with_warnings?.length)showNotice(`Impor selesai dengan ${result.rows_with_warnings.length} peringatan.`,'info');await loadSymbols();forgetReset(viewResetKey);loadOverview();loadData()}catch(error){showNotice(error.message,'error')}}
  function applyRange(days){if(days==='custom'){byId('fromDate').focus();return}const end=new Date();const start=new Date();start.setDate(end.getDate()-(Number(days)-1));byId('fromDate').value=isoDate(start);byId('toDate').value=isoDate(end);document.querySelectorAll('.range-btn').forEach(button=>button.classList.toggle('active',button.dataset.range===String(days)));updateFilterState();updateExportLinks()}

  function setActiveTab(tabId){
    const buttons=[...document.querySelectorAll('.section-nav [data-tab-target]')];
    const panels=[...document.querySelectorAll('[data-tab-panel]')];
    if(!panels.some(panel=>panel.dataset.tabPanel===tabId))tabId='results';
    buttons.forEach(button=>{
      const active=button.dataset.tabTarget===tabId;
      button.setAttribute('aria-selected',String(active));
      button.tabIndex=active?0:-1;
    });
    panels.forEach(panel=>{
      const active=panel.dataset.tabPanel===tabId;
      panel.hidden=!active;
      panel.classList.toggle('is-active',active);
      panel.setAttribute('aria-hidden',String(!active));
      if(panel.tagName.toLowerCase()==='details')panel.open=active;
    });
  }
  function navigateWorkspace(tabId){setActiveTab(tabId)}
  document.querySelectorAll('.section-nav [data-tab-target]').forEach(button=>button.addEventListener('click',()=>navigateWorkspace(button.dataset.tabTarget)));

  byId('dataForm').addEventListener('submit',event=>{event.preventDefault();forgetReset(viewResetKey);setActiveTab('results');updateFilterState();loadData()});
  byId('resetView').addEventListener('click',resetView);
  byId('refreshAll').addEventListener('click',()=>{loadOverview();loadRuns();loadData();pollJob()});
  byId('resetJob').addEventListener('click',resetJob);
  byId('importButton').addEventListener('click',importCsv);
  byId('loadBroker').addEventListener('click',loadBroker);
  byId('loadMarketBroker').addEventListener('click',loadMarketBroker);
  byId('loadFeatures').addEventListener('click',loadFeatures);
  byId('runBacktest').addEventListener('click',runBacktest);
  byId('runPositionSize').addEventListener('click',runPositionSize);
  byId('brokerDays').addEventListener('change',updateExportLinks);
  byId('marketBrokerDays').addEventListener('change',updateExportLinks);
  byId('symbols').addEventListener('input',()=>{updateFilterState();updateExportLinks()});
  byId('fromDate').addEventListener('change',()=>{updateFilterState();updateExportLinks()});
  byId('toDate').addEventListener('change',()=>{updateFilterState();updateExportLinks()});
  document.querySelectorAll('.range-btn').forEach(button=>button.addEventListener('click',()=>applyRange(button.dataset.range)));
  document.querySelectorAll('[data-analysis-tab]').forEach(button=>button.addEventListener('click',()=>{analysisTab=button.dataset.analysisTab;document.querySelectorAll('[data-analysis-tab]').forEach(item=>item.classList.toggle('active',item===button));renderAnalysis()}));
  document.querySelector('[data-job="sync"]').addEventListener('click',()=>runJob('/ui/api/jobs/sync-symbols'));
  document.querySelector('[data-job="daily"]').addEventListener('click',()=>runJob('/ui/api/jobs/daily',{end:byId('dailyEnd').value||null}));
  document.querySelector('[data-job="market-broker"]').addEventListener('click',()=>{const start=byId('fromDate').value||byId('dailyEnd').value;const end=byId('toDate').value||byId('dailyEnd').value;if(!start||!end){showNotice('Isi rentang tanggal pada filter utama terlebih dahulu.','error');return}runJob('/ui/api/jobs/market-broker-summary',{start,end})});
  document.querySelector('[data-job="index-summary"]').addEventListener('click',()=>{const start=byId('fromDate').value||byId('dailyEnd').value;const end=byId('toDate').value||byId('dailyEnd').value;if(!start||!end){showNotice('Isi rentang tanggal pada filter utama terlebih dahulu.','error');return}runJob('/ui/api/jobs/index-summary',{start,end})});
  document.querySelector('[data-job="corporate-actions"]').addEventListener('click',()=>{const start=byId('fromDate').value||byId('dailyEnd').value;const end=byId('toDate').value||byId('dailyEnd').value;runJob('/ui/api/jobs/corporate-actions',{symbols:byId('actionSymbols').value,start,end})});
  document.querySelector('[data-job="adjust"]').addEventListener('click',()=>runJob('/ui/api/jobs/adjust',{symbols:byId('adjustSymbols').value}));
  byId('backfillForm').addEventListener('submit',event=>{event.preventDefault();runJob('/ui/api/jobs/backfill',{symbols:byId('backfillSymbols').value,start:byId('backfillStart').value,end:byId('backfillEnd').value})});
  byId('dataForm').addEventListener('submit',()=>{loadIndexSummary();loadCatalog()});
  setDefaults();setActiveTab('results');updateFilterState();loadSymbols();loadOverview();loadRuns();loadData();loadIndexSummary();loadCatalog();pollJob();
</script>
</body>
</html>"""
